# Generated by Django 5.2.15 on 2026-07-07 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEventLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('license_key', models.CharField(max_length=100)),
                ('tenant_name', models.CharField(max_length=255)),
                ('caller_phone', models.CharField(max_length=50)),
                ('caller_name', models.CharField(default='Customer', max_length=255)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('expired', 'expired'), ('blocked', 'blocked'), ('simulated', 'simulated')], max_length=20)),
                ('duration_ms', models.IntegerField()),
                ('details', models.TextField()),
                ('raw_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerConsoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('error', 'error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('phase', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('1-month', '1-month'), ('3-month', '3-month'), ('6-month', '6-month'), ('12-month', '12-month')], default='1-month', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired'), ('blocked', 'blocked')], default='active', max_length=20)),
                ('waba_token', models.TextField(blank=True, default='')),
                ('phone_number_id', models.CharField(blank=True, default='', max_length=100)),
                ('template_name', models.CharField(default='missed_call_recovery', max_length=100)),
                ('language_code', models.CharField(default='en_US', max_length=20)),
                ('calls_count', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
            ],
        ),
    ]
