# Generated by Django 5.2.16 on 2026-07-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique identifier (e.g. 1-month, 3-month, 6-month, 12-month)', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('duration_days', models.IntegerField(default=30)),
                ('price_rupees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_equivalent', models.CharField(blank=True, default='', max_length=50)),
                ('discount_badge', models.CharField(blank=True, default='', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('features_list', models.TextField(blank=True, default='', help_text='Enter one feature per line')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending'), ('expired', 'expired'), ('blocked', 'blocked')], default='active', max_length=20),
        ),
    ]
